### ISSUE TITLE
Provide support for goose and create-react-app

### ISSUE THREAD

**Issue by psankar** [McMenemy/GoDoRP#2]
This is an extremely handy starter project. Thanks a lot.

I am filing this as an enhancement (not a bug). It will be nice if you can integrate [create-react-app](https://github.com/facebookincubator/create-react-app) for the front-end and [goose](https://github.com/pressly/goose) (or some such) database migration tool, on the api side.

Creating tables and databases should be done in a reliable, verifiable way to ensure that two instances of a API service may not run the same sql commands, etc.

**Comment by McMenemy** [comment]
The frontend is already using create-react-app and the docker prod/dev options are built on top of it.

But a migration tool is definitly needed. Currently, do not have time to work on this project but pull requests are welcome if you want to add the feature =).
